### ISSUE TITLE
Generic-инстансы

### ISSUE THREAD

**Issue by delfigamer** [DenDragonB/echobot#1]
https://github.com/DenDragonB/echobot/blob/eab9a733042a38d49c7f2a17892d7791c6c5b244/src/Bot.hs#L9-L23

Вместо явного расписывания таких парсеров, можно использовать [автоматически генерируемые](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/generics.html?highlight=derivegeneric#extension-DeriveGeneric):
```hs
data Config = Config
  { aboutText     :: String
  , helpText      :: String
  , repeatText1   :: String
  , repeatText2   :: String
  , repeatDefault :: URep
  }
  deriving (Show, Eq, Generic) -- requires -XDeriveGeneric
instance Aeson.FromJSON Config

  -- alternatively, with -XDeriveGeneric and -XDeriveAnyType
data Config = Config {...}
  deriving (Show, Eq, Generic, Aeson.FromJSON)
```

В случае, когда в структуре у селекторов есть дополнительный префикс, которого нет в жисоне - можно настроить модификацию с использованием функций из [aeson-casing](https://hackage.haskell.org/package/aeson-casing-0.2.0.0/docs/Data-Aeson-Casing.html):
```hs
instance Aeson.FromJSON SomeType where
  parseJSON = Aeson.genericParseJSON $ Aeson.Casing.aesonPrefix Aeson.Casing.camelCase
```

**Comment by DenDragonB** [comment]
Где это было возможно - сделал.
