### ISSUE TITLE
Вк лонгполлинг

### ISSUE THREAD

**Issue by ghost** [DenDragonB/echobot#11]
Из [дока](https://vk.com/dev/bots_longpoll)
> В ответ на запрос сервер может вернуть одну из ошибок:
{"failed":1,"ts":30}
{"failed":2}
{"failed":3}
"failed":1 — история событий устарела или была частично утеряна, приложение может получать события далее, используя новое значение ts из ответа.
"failed":2 — истекло время действия ключа, нужно заново получить key методом groups.getLongPollServer.
"failed":3 — информация утрачена, нужно запросить новые key и ts методом groups.getLongPollServer.
Обратите внимание, объекты в сообщении об ошибке могут содержат поля, не описанные в документации. Их необходимо игнорировать и не пытаться обработать.

По хорошему эти кейсы надо обрабатывать

**Comment by DenDragonB** [comment]
Добавил
