### ISSUE TITLE
main.yaml

### ISSUE THREAD

**Issue by ghost** [DenDragonB/echobot#12]
В `app`, так же как и в `src` не должно быть ничего кроме исходных файлов.
Также, сейчас этот файл находится в репозитории гита, что делает сложным такой воркфлоу:
* `git clone ...`
* настроил конфиг (со своими токенами)
* запустил
* разработчик запушил обновление
* `git pull` не работает, потому что в рабочей директории незакоммиченные изменения
* приходится `git reset main.yaml`
* `git pull` теперь работает
* теперь нужно заполнить main.yaml заново
* только теперь можно потестить

Обычно конфиг хранится не там где он читается (а еще лучше когда можно аргументом коммандной строки задать конфиг), а тот файл из которого он читается занесен в .gitignore, чтобы пользователи могли его настроить под себя и он не мешал обновлениям

**Comment by DenDragonB** [comment]
А как поймут куда его нужно поместить?

**Comment by ghost** [comment]
Хороший вопрос. Это лучше описать в `README.md`

**Comment by DenDragonB** [comment]
сделал
