### ISSUE TITLE
Мутабельный хендл

### ISSUE THREAD

**Issue by delfigamer** [DenDragonB/echobot#3]
https://github.com/DenDragonB/echobot/blob/eab9a733042a38d49c7f2a17892d7791c6c5b244/src/Bot.hs#L25-L29

При обычном использовании хендл-паттерна, сам по себе хендл - это иммутабельный объект, который передаётся в функции на манер ридера.
Если требуется хранить переменное состояние, то это можно решить такими методами:
1. Хранить в хендле мутабельную ссылку - `STRef`, `IORef`, `TVar`.
2. Сделать хендл параметризованным по монаде и хранить в нём функцию-аксессор и функцию-мутатор состояния:
   ```hs
   data Handle m = Handle
     { config :: Config
     , getUsers :: m [Users]
     , updateUsers :: ([Users] -> [Users]) -> m ()
     }
   ```
С другой стороны, если хочется оставить как есть - это тоже имеет право на жизнь; однако, в таком случае, для этой структуры более верным названием будет `State` - оно более точно передаст её назначение, и не будет сбивать с толку неверными ассоциациями с классическим хендл-паттерном.

**Comment by DenDragonB** [comment]
разделил
