### ISSUE TITLE
Перебор данных в списке вместо таблицы

### ISSUE THREAD

**Issue by delfigamer** [DenDragonB/echobot#4]
https://github.com/DenDragonB/echobot/blob/eab9a733042a38d49c7f2a17892d7791c6c5b244/src/Bot.hs#L60-L68

Здесь вместо плоского списка `[User]` больше по смыслу подошла бы таблица [`Data.Map.Strict.Map UID User`](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Strict.html), или даже хеш-таблица [`Data.HashMap.Strict.HashMap UID User`](https://hackage.haskell.org/package/unordered-containers-0.2.14.0/docs/Data-HashMap-Strict.html):
1. Она лучше документирует тот факт, что `UID` - это именно идентификатор пользователя, под которым сохраняются все его данные, а не просто одно из его свойств.
2. Поиск по таблице гораздо быстрее, чем по списку - логарифмическое время против линейного.
3. В отличие от списка, таблица автоматически гарантирует инвариант: не более одного пользователя на каждое значение `UID`.

**Comment by DenDragonB** [comment]
Сделал
