### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by ghost** [DenDragonB/echobot#7]
https://rizzoma.com/topic/c27faf1cfa188c1120f59af4c35e6099/0_b_9n8n_8jl2r/
> Весь код отформатирован через hindent.

Вместо hindent можно использовать любой форматтер: brittany, ormolu, stylish-haskell и др.

**Comment by DenDragonB** [comment]
отформатировал stylish-haskell

**Comment by ghost** [comment]
Меня смущал форматтинг вот такого вида:
```
setCommand [] newUser = [User { uName    = uName newUser
                                  , uID      = uID newUser
                                  , uRep     = uRep newUser
                                  , uSentRep = uSentRep newUser
                                  } ]
```
Но стайлиш его почему то не фиксит, ладно
