### ISSUE TITLE
Разделить стейт и окружение

### ISSUE THREAD

**Issue by ghost** [DenDragonB/echobot#8]
Сейчас Handle (который, как замечено в #3 вообще-то стейт)
```haskell
data Handle = Handle
    { hConfig  :: Config
    , hBot     :: Bot.Handle
    , hLogger  :: Logger.Handle
    , server   :: LongPollServer
    , offset   :: String
    , response :: Maybe Response
    }
```
содержит в себе два типа полей: статические, которые не меняются во время выполнения: конфиг, лонг полл сервер (который по идее должен меняться, вроде, когда key устаревает), оффсет. И динамический респонс (мутабельный стейт). Хендлы бота и логгера так же можно разделить на две составляющие. Класть response  в стейт и строить на этом архитектуру дело сомнительное, и я пока хотел бы убедиться что все функционально работает, и уже потом пытаться понять почему ты решил так сделать и в чем приимущества. Но совмещать в одном типе данных две разные штуки -- стейт и статическое окружение не стоит, энивей, если в этом нет необходимости.

Обычно для хранения окружения используют `ReaderT`, а для состояния либо `StateT` либо в ридер кладут `MVar`, `TVar` или `IORef`, но можно и оставить и в виде `s -> IO s`

**Comment by DenDragonB** [comment]
И что в данном случае будет лучше?

**Comment by ghost** [comment]
Разделить хендл на стейт (динамическая мутабельная часть) и на окружение (статическая часть, которая создается на старте, но в процессе выполнения не модифицируется). Как - это уже не так важно

**Comment by DenDragonB** [comment]
разделил
